version: 2.1

jobs:
  test-example:
    parameters:
      example-app-name:
        type: string
      path:
        type: string
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    environment:
      BUILDING_BLOCK: digital-registries
      TESTED_APPLICATION: << parameters.example-app-name >> 
      TEST_RESULT_REPORT_FILENAME: example_result.message
    steps:
      - checkout
      - run:
          name: Execute tests
          command: |
            # Execute application test_entrypoint.sh in background. 
            chmod u+x <<parameters.path >> test_entrypoint.sh &
            cd <<parameters.path >> 
            ./test_entrypoint.sh &
            
            # Execute gherkin tests for given application 
            cd ./../../test/
            EXAMPLE_APPLICATION_ABSOLUTE_PATH=<<parameters.path >> docker-compose up --build gherkin-test-report
      - checkout 
      - run:
          name: Export test results 
          command: | 
            # Save test execution result path to environment:
            export TEST_RESULTS_PATH=${CIRCLE_WORKING_DIRECTORY}/test/tests_result/
            cd .circleci/reportExport 
            yarn install 
            yarn run export-mongo 

            
workflows:
  test_everything:
    jobs:
      # This part is replaced programatically by test executions for all example applications 
      - test-example:
          name: 'example-application-name'
          path-info: 'Path to example application directory with test_entrypoint.sh'
